#!/usr/bin/env python3
import os
import glob
import re

def translate_subpages():
    # Common translations for all sub-pages
    common_translations = {
        # Meta tags
        'Parts Trading Company': 'Компания Parts Trading',
        'India\'s #1': 'Ведущий в Индии',
        'Browse complete': 'Просмотр полного',
        'spare parts categories': 'каталога запчастей',
        'Engine parts, brakes, transmission, filters, hydraulics and more': 'Детали двигателя, тормоза, трансмиссия, фильтры, гидравлика и многое другое',
        '5000+ parts in stock': 'Более 5000 запчастей на складе',
        'Fast shipping across India': 'Быстрая доставка по всей Индии',
        'Volvo spare parts categories': 'Категории запчастей Volvo',
        'Volvo engine parts': 'Детали двигателя Volvo',
        'Volvo brake parts': 'Тормозные детали Volvo',
        'Volvo transmission parts': 'Детали трансмиссии Volvo',
        'Volvo filters': 'Фильтры Volvo',
        'Volvo hydraulic parts': 'Гидравлические детали Volvo',
        'heavy equipment parts': 'запчасти для тяжелого оборудования',
        'truck parts supplier': 'поставщик запчастей для грузовиков',
        'Volvo parts dealer': 'дилер запчастей Volvo',
        'spare parts India': 'запчасти Индия',
        'automotive parts Mumbai': 'автозапчасти Мумбаи',
        
        # Navigation
        'HOME': 'ГЛАВНАЯ',
        'BRANDS': 'БРЕНДЫ',
        'PRODUCTS': 'ПРОДУКТЫ',
        'FAQ': 'ЧАВО',
        'CONTACT': 'КОНТАКТЫ',
        'PARTS TRADING': 'PARTS TRADING',
        'COMPANY': 'КОМПАНИЯ',
        
        # Page titles
        'Volvo Spare Parts Categories': 'Категории запчастей Volvo',
        'Scania Spare Parts Categories': 'Категории запчастей Scania',
        'Komatsu Spare Parts Categories': 'Категории запчастей Komatsu',
        'Caterpillar Spare Parts Categories': 'Категории запчастей Caterpillar',
        'Hitachi Spare Parts Categories': 'Категории запчастей Hitachi',
        'Kobelco Spare Parts Categories': 'Категории запчастей Kobelco',
        
        # Category names
        'Engine Components': 'Компоненты двигателя',
        'Fuel System Components': 'Компоненты топливной системы',
        'Transmission & Differential Components': 'Компоненты трансмиссии и дифференциала',
        'Braking System Components': 'Компоненты тормозной системы',
        'Steering & Suspension Parts': 'Детали рулевого управления и подвески',
        'Hydraulic Systems & Connectors': 'Гидравлические системы и соединители',
        'Air & Fluid Filtration Systems': 'Системы фильтрации воздуха и жидкости',
        'Lighting & Exterior Body Components': 'Осветительные и внешние кузовные компоненты',
        'Fasteners, Hardware & Accessories': 'Крепежные элементы, оборудование и аксессуары',
        'Compressed Air System Components': 'Компоненты системы сжатого воздуха',
        'Clutch & Transmission Components': 'Компоненты сцепления и трансмиссии',
        'Miscellaneous Parts': 'Различные детали',
        
        # Buttons and UI
        'View Products': 'Посмотреть продукты',
        'Back to Categories': 'Назад к категориям',
        'Search Parts': 'Найти запчасти',
        'Contact Us': 'Связаться с нами',
        'WhatsApp Us': 'Напишите нам в WhatsApp',
        'Get Quote': 'Получить предложение',
        
        # Footer
        'Contact Information': 'Контактная информация',
        'Landline': 'Стационарный телефон',
        'Mobile': 'Мобильный телефон',
        'Email': 'Электронная почта',
        'Address': 'Адрес',
        'Save Contact': 'Сохранить контакт',
        'Find Us on Google Maps': 'Найдите нас на Google Maps',
        'Open in Google Maps': 'Открыть в Google Maps',
        '© Parts Trading Company. All rights reserved.': '© Компания Parts Trading. Все права защищены.',
        
        # Product specific
        'Part Number': 'Номер детали',
        'Description': 'Описание',
        'Brand': 'Бренд',
        'Category': 'Категория',
        'Availability': 'Наличие',
        'In Stock': 'На складе',
        'Out of Stock': 'Нет в наличии',
        'Price': 'Цена',
        'Request Quote': 'Запросить цену',
        'Add to Cart': 'Добавить в корзину',
        'Product Details': 'Детали продукта',
        'Specifications': 'Спецификации',
        'Related Products': 'Похожие продукты',
        'Customer Reviews': 'Отзывы клиентов',
        'Write a Review': 'Написать отзыв',
        'Rating': 'Рейтинг',
        'stars': 'звезд',
        'Verified Purchase': 'Подтвержденная покупка',
        'Helpful': 'Полезно',
        'Not Helpful': 'Не полезно',
        'Report': 'Сообщить',
        'Share': 'Поделиться',
        'Print': 'Печать',
        'Email to Friend': 'Отправить другу',
        'Wishlist': 'Список желаний',
        'Compare': 'Сравнить',
        'Quick View': 'Быстрый просмотр',
        'Full Description': 'Полное описание',
        'Technical Data': 'Технические данные',
        'Installation Guide': 'Руководство по установке',
        'Warranty Information': 'Информация о гарантии',
        'Return Policy': 'Политика возврата',
        'Shipping Information': 'Информация о доставке',
        'Payment Options': 'Варианты оплаты',
        'Secure Payment': 'Безопасная оплата',
        'Free Shipping': 'Бесплатная доставка',
        'Express Delivery': 'Экспресс-доставка',
        'Same Day Dispatch': 'Отправка в тот же день',
        'Next Day Delivery': 'Доставка на следующий день',
        'International Shipping': 'Международная доставка',
        'Track Order': 'Отследить заказ',
        'Order History': 'История заказов',
        'Account': 'Аккаунт',
        'Login': 'Войти',
        'Register': 'Зарегистрироваться',
        'Logout': 'Выйти',
        'My Account': 'Мой аккаунт',
        'Profile': 'Профиль',
        'Settings': 'Настройки',
        'Password': 'Пароль',
        'Change Password': 'Изменить пароль',
        'Forgot Password': 'Забыли пароль',
        'Reset Password': 'Сбросить пароль',
        'New Password': 'Новый пароль',
        'Confirm Password': 'Подтвердить пароль',
        'Current Password': 'Текущий пароль',
        'Update Profile': 'Обновить профиль',
        'Personal Information': 'Личная информация',
        'Billing Address': 'Адрес для выставления счетов',
        'Shipping Address': 'Адрес доставки',
        'Phone Number': 'Номер телефона',
        'Date of Birth': 'Дата рождения',
        'Gender': 'Пол',
        'Male': 'Мужской',
        'Female': 'Женский',
        'Other': 'Другой',
        'Prefer not to say': 'Предпочитаю не указывать',
        'Newsletter': 'Новостная рассылка',
        'Subscribe': 'Подписаться',
        'Unsubscribe': 'Отписаться',
        'Terms & Conditions': 'Условия использования',
        'Privacy Policy': 'Политика конфиденциальности',
        'Cookie Policy': 'Политика использования файлов cookie',
        'Refund Policy': 'Политика возврата средств',
        'Shipping Policy': 'Политика доставки',
        'About Us': 'О нас',
        'Our Story': 'Наша история',
        'Mission & Vision': 'Миссия и видение',
        'Team': 'Команда',
        'Careers': 'Карьера',
        'Press': 'Пресса',
        'Blog': 'Блог',
        'News': 'Новости',
        'Events': 'События',
        'Support': 'Поддержка',
        'Help Center': 'Центр помощи',
        'FAQ': 'Часто задаваемые вопросы',
        'Contact Support': 'Связаться с поддержкой',
        'Live Chat': 'Онлайн-чат',
        'Phone Support': 'Телефонная поддержка',
        'Email Support': 'Поддержка по электронной почте',
        'Ticket System': 'Система тикетов',
        'Knowledge Base': 'База знаний',
        'User Manuals': 'Пользовательские руководства',
        'Video Tutorials': 'Видеоуроки',
        'Troubleshooting': 'Устранение неполадок',
        'Maintenance Guides': 'Руководства по обслуживанию',
        'Installation Guides': 'Руководства по установке',
        'Safety Information': 'Информация о безопасности',
        'Recall Information': 'Информация об отзыве',
        'Product Recalls': 'Отзыв продукции',
        'Safety Alerts': 'Предупреждения о безопасности',
        'Quality Assurance': 'Обеспечение качества',
        'Quality Control': 'Контроль качества',
        'Testing & Certification': 'Тестирование и сертификация',
        'ISO Certified': 'Сертифицировано по ISO',
        'CE Marked': 'С маркировкой CE',
        'FDA Approved': 'Одобрено FDA',
        'UL Listed': 'В списке UL',
        'RoHS Compliant': 'Соответствует RoHS',
        'REACH Compliant': 'Соответствует REACH',
        'Conflict Minerals Free': 'Без конфликтных минералов',
        'Environmentally Friendly': 'Экологически безопасный',
        'Energy Efficient': 'Энергоэффективный',
        'Recyclable': 'Перерабатываемый',
        'Biodegradable': 'Биоразлагаемый',
        'Sustainable': 'Устойчивый',
        'Green Technology': 'Зеленая технология',
        'Carbon Neutral': 'Углеродно-нейтральный',
        'Zero Waste': 'Нулевые отходы',
        'Circular Economy': 'Циклическая экономика',
        'Corporate Social Responsibility': 'Корпоративная социальная ответственность',
        'Community Outreach': 'Работа с сообществом',
        'Charitable Giving': 'Благотворительность',
        'Volunteer Programs': 'Волонтерские программы',
        'Educational Initiatives': 'Образовательные инициативы',
        'Environmental Protection': 'Защита окружающей среды',
        'Wildlife Conservation': 'Сохранение дикой природы',
        'Tree Planting': 'Посадка деревьев',
        'Clean Energy': 'Чистая энергия',
        'Solar Power': 'Солнечная энергия',
        'Wind Power': 'Ветровая энергия',
        'Hydroelectric Power': 'Гидроэлектроэнергия',
        'Geothermal Energy': 'Геотермальная энергия',
        'Biomass Energy': 'Биоэнергия',
        'Nuclear Energy': 'Ядерная энергия',
        'Fossil Fuels': 'Ископаемое топливо',
        'Coal': 'Уголь',
        'Oil': 'Нефть',
        'Natural Gas': 'Природный газ',
        'Petroleum': 'Нефтепродукты',
        'Diesel': 'Дизельное топливо',
        'Gasoline': 'Бензин',
        'LPG': 'Сжиженный нефтяной газ',
        'CNG': 'Сжатый природный газ',
        'Electric': 'Электрический',
        'Hybrid': 'Гибридный',
        'Plug-in Hybrid': 'Подключаемый гибрид',
        'Battery Electric': 'Аккумуляторный электрический',
        'Fuel Cell': 'Топливный элемент',
        'Hydrogen': 'Водород',
        'Biodiesel': 'Биодизель',
        'Ethanol': 'Этанол',
        'Methanol': 'Метанол',
        'Propane': 'Пропан',
        'Butane': 'Бутан',
        'Kerosene': 'Керосин',
        'Jet Fuel': 'Авиационное топливо',
        'Marine Fuel': 'Морское топливо',
        'Heavy Fuel Oil': 'Тяжелое топливо',
        'Light Fuel Oil': 'Легкое топливо',
        'Residual Fuel Oil': 'Остаточное топливо',
        'Distillate Fuel Oil': 'Дистиллятное топливо',
        'Lubricating Oil': 'Смазочное масло',
        'Hydraulic Oil': 'Гидравлическое масло',
        'Transmission Oil': 'Трансмиссионное масло',
        'Engine Oil': 'Моторное масло',
        'Gear Oil': 'Масло для редуктора',
        'Brake Fluid': 'Тормозная жидкость',
        'Coolant': 'Охлаждающая жидкость',
        'Antifreeze': 'Антифриз',
        'Windshield Washer Fluid': 'Жидкость для омывателя лобового стекла',
        'Power Steering Fluid': 'Жидкость для гидроусилителя руля',
        'Clutch Fluid': 'Жидкость сцепления',
        'Differential Oil': 'Масло дифференциала',
        'Transfer Case Oil': 'Масло раздаточной коробки',
        'Manual Transmission Oil': 'Масло механической коробки передач',
        'Automatic Transmission Fluid': 'Жидкость автоматической коробки передач',
        'CVT Fluid': 'Жидкость вариатора',
        'Power Take-off Oil': 'Масло коробки отбора мощности',
        'Final Drive Oil': 'Масло главной передачи',
        'Axle Oil': 'Масло моста',
        'Hub Oil': 'Масло ступицы',
        'Wheel Bearing Grease': 'Смазка подшипников колес',
        'Universal Joint Grease': 'Смазка карданного шарнира',
        'Chassis Grease': 'Смазка шасси',
        'Ball Joint Grease': 'Смазка шарового шарнира',
        'Tie Rod Grease': 'Смазка рулевой тяги',
        'Steering Gear Grease': 'Смазка рулевого механизма',
        'Suspension Grease': 'Смазка подвески',
        'Shock Absorber Oil': 'Масло амортизатора',
        'Air Filter Oil': 'Масло воздушного фильтра',
        'Fuel Filter': 'Топливный фильтр',
        'Oil Filter': 'Масляный фильтр',
        'Air Filter': 'Воздушный фильтр',
        'Hydraulic Filter': 'Гидравлический фильтр',
        'Transmission Filter': 'Фильтр трансмиссии',
        'Cabin Filter': 'Фильтр салона',
        'Pollen Filter': 'Пыльцевой фильтр',
        'Charcoal Filter': 'Угольный фильтр',
        'HEPA Filter': 'HEPA фильтр',
        'Water Separator': 'Водоотделитель',
        'Fuel Water Separator': 'Топливный водоотделитель',
        'Oil Water Separator': 'Масляный водоотделитель',
        'Air Water Separator': 'Воздушный водоотделитель',
        'Moisture Separator': 'Влагосепаратор',
        'Dust Separator': 'Пылеотделитель',
        'Particle Separator': 'Сепаратор частиц',
        'Centrifugal Separator': 'Центробежный сепаратор',
        'Magnetic Separator': 'Магнитный сепаратор',
        'Gravity Separator': 'Гравитационный сепаратор',
        'Cyclone Separator': 'Циклонный сепаратор',
        'Bag Filter': 'Рукавный фильтр',
        'Cartridge Filter': 'Картриджный фильтр',
        'Panel Filter': 'Панельный фильтр',
        'Pleated Filter': 'Складчатый фильтр',
        'Spun Filter': 'Нетканый фильтр',
        'Wire Mesh Filter': 'Сетчатый фильтр',
        'Sintered Filter': 'Спеченный фильтр',
        'Ceramic Filter': 'Керамический фильтр',
        'Paper Filter': 'Бумажный фильтр',
        'Felt Filter': 'Войлочный фильтр',
        'Foam Filter': 'Пенный фильтр',
        'Stainless Steel Filter': 'Нержавеющий фильтр',
        'Brass Filter': 'Латунный фильтр',
        'Aluminum Filter': 'Алюминиевый фильтр',
        'Plastic Filter': 'Пластиковый фильтр',
        'Rubber Filter': 'Резиновый фильтр',
        'Silicone Filter': 'Силиконовый фильтр',
        'Teflon Filter': 'Тефлоновый фильтр',
        'Nylon Filter': 'Нейлоновый фильтр',
        'Polyester Filter': 'Полиэфирный фильтр',
        'Polypropylene Filter': 'Полипропиленовый фильтр',
        'Polyethylene Filter': 'Полиэтиленовый фильтр',
        'PVC Filter': 'ПВХ фильтр',
        'ABS Filter': 'АБС фильтр',
        'PC Filter': 'ПК фильтр',
        'POM Filter': 'ПОМ фильтр',
        'PBT Filter': 'ПБТ фильтр',
        'PA Filter': 'ПА фильтр',
        'PPS Filter': 'ППС фильтр',
        'PEEK Filter': 'ПИК фильтр',
        'PTFE Filter': 'ПТФЭ фильтр',
        'FEP Filter': 'ФЭП фильтр',
        'PFA Filter': 'ПФА фильтр',
        'ETFE Filter': 'ЭТФЭ фильтр',
        'ECTFE Filter': 'ЭКТФЭ фильтр',
        'PVDF Filter': 'ПВДФ фильтр',
        'ECTFE Filter': 'ЭКТФЭ фильтр',
        'PCTFE Filter': 'ПКТФЭ фильтр',
        'FEP Filter': 'ФЭП фильтр',
        'PFA Filter': 'ПФА фильтр',
        'ETFE Filter': 'ЭТФЭ фильтр',
        'ECTFE Filter': 'ЭКТФЭ фильтр',
        'PVDF Filter': 'ПВДФ фильтр',
        'ECTFE Filter': 'ЭКТФЭ фильтр',
        'PCTFE Filter': 'ПКТФЭ фильтр'
    }
    
    # Get all HTML files in pages directory
    html_files = glob.glob('pages/**/*.html', recursive=True)
    html_files.extend(glob.glob('pages/*.html'))
    
    print(f"Found {len(html_files)} HTML files to translate")
    
    for file_path in html_files:
        print(f"Translating: {file_path}")
        
        # Read the file
        with open(file_path, 'r', encoding='utf-8') as f:
            content = f.read()
        
        # Change language to Russian
        content = content.replace('lang="en"', 'lang="ru"')
        
        # Apply translations
        for english, russian in common_translations.items():
            content = content.replace(english, russian)
        
        # Fix CSS and JS paths for subdirectory
        content = content.replace('href="assets/', 'href="../assets/')
        content = content.replace('src="assets/', 'src="../assets/')
        content = content.replace('href="database/', 'href="../database/')
        content = content.replace('src="database/', 'src="../database/')
        
        # Write back to file
        with open(file_path, 'w', encoding='utf-8') as f:
            f.write(content)
    
    print("✅ All sub-pages translated to Russian!")

if __name__ == "__main__":
    translate_subpages()






