#!/usr/bin/env python3
import os
import glob
import re

def translate_subpages_arabic():
    # Common translations for all sub-pages to Arabic
    common_translations = {
        # Meta tags
        'Parts Trading Company': 'شركة تداول قطع الغيار',
        'India\'s #1': 'الرائدة في الهند',
        'Browse complete': 'تصفح كامل',
        'spare parts categories': 'فئات قطع الغيار',
        'Engine parts, brakes, transmission, filters, hydraulics and more': 'أجزاء المحرك، الفرامل، ناقل الحركة، الفلاتر، الهيدروليكا والمزيد',
        '5000+ parts in stock': 'أكثر من 5000 قطعة في المخزون',
        'Fast shipping across India': 'شحن سريع عبر الهند',
        'Volvo spare parts categories': 'فئات قطع غيار Volvo',
        'Volvo engine parts': 'أجزاء محرك Volvo',
        'Volvo brake parts': 'أجزاء فرامل Volvo',
        'Volvo transmission parts': 'أجزاء ناقل حركة Volvo',
        'Volvo filters': 'فلاتر Volvo',
        'Volvo hydraulic parts': 'أجزاء هيدروليكية Volvo',
        'heavy equipment parts': 'قطع غيار المعدات الثقيلة',
        'truck parts supplier': 'مورد قطع غيار الشاحنات',
        'Volvo parts dealer': 'تاجر قطع غيار Volvo',
        'spare parts India': 'قطع غيار الهند',
        'automotive parts Mumbai': 'قطع غيار السيارات مومباي',
        
        # Navigation
        'HOME': 'الرئيسية',
        'BRANDS': 'العلامات التجارية',
        'PRODUCTS': 'المنتجات',
        'FAQ': 'الأسئلة الشائعة',
        'CONTACT': 'اتصل بنا',
        'PARTS TRADING': 'تداول قطع الغيار',
        'COMPANY': 'الشركة',
        
        # Page titles
        'Volvo Spare Parts Categories': 'فئات قطع غيار Volvo',
        'Scania Spare Parts Categories': 'فئات قطع غيار Scania',
        'Komatsu Spare Parts Categories': 'فئات قطع غيار Komatsu',
        'Caterpillar Spare Parts Categories': 'فئات قطع غيار Caterpillar',
        'Hitachi Spare Parts Categories': 'فئات قطع غيار Hitachi',
        'Kobelco Spare Parts Categories': 'فئات قطع غيار Kobelco',
        
        # Category names
        'Engine Components': 'مكونات المحرك',
        'Fuel System Components': 'مكونات نظام الوقود',
        'Transmission & Differential Components': 'مكونات ناقل الحركة والتفاضل',
        'Braking System Components': 'مكونات نظام الفرامل',
        'Steering & Suspension Parts': 'أجزاء التوجيه والتعليق',
        'Hydraulic Systems & Connectors': 'الأنظمة الهيدروليكية والموصلات',
        'Air & Fluid Filtration Systems': 'أنظمة ترشيح الهواء والسوائل',
        'Lighting & Exterior Body Components': 'مكونات الإضاءة والهيكل الخارجي',
        'Fasteners, Hardware & Accessories': 'المثبتات والأجهزة والملحقات',
        'Compressed Air System Components': 'مكونات نظام الهواء المضغوط',
        'Clutch & Transmission Components': 'مكونات القابض وناقل الحركة',
        'Miscellaneous Parts': 'قطع متنوعة',
        
        # Buttons and UI
        'View Products': 'عرض المنتجات',
        'Back to Categories': 'العودة إلى الفئات',
        'Search Parts': 'البحث عن قطع الغيار',
        'Contact Us': 'اتصل بنا',
        'WhatsApp Us': 'تواصل معنا عبر واتساب',
        'Get Quote': 'احصل على عرض سعر',
        
        # Footer
        'Contact Information': 'معلومات الاتصال',
        'Landline': 'الهاتف الثابت',
        'Mobile': 'الجوال',
        'Email': 'البريد الإلكتروني',
        'Address': 'العنوان',
        'Save Contact': 'حفظ جهة الاتصال',
        'Find Us on Google Maps': 'اعثر علينا على خرائط جوجل',
        'Open in Google Maps': 'افتح في خرائط جوجل',
        '© Parts Trading Company. All rights reserved.': '© شركة تداول قطع الغيار. جميع الحقوق محفوظة.',
        
        # Product specific
        'Part Number': 'رقم القطعة',
        'Description': 'الوصف',
        'Brand': 'العلامة التجارية',
        'Category': 'الفئة',
        'Availability': 'التوفر',
        'In Stock': 'متوفر في المخزون',
        'Out of Stock': 'غير متوفر في المخزون',
        'Price': 'السعر',
        'Request Quote': 'طلب عرض سعر',
        'Add to Cart': 'أضف إلى السلة',
        'Product Details': 'تفاصيل المنتج',
        'Specifications': 'المواصفات',
        'Related Products': 'المنتجات ذات الصلة',
        'Customer Reviews': 'تقييمات العملاء',
        'Write a Review': 'اكتب تقييماً',
        'Rating': 'التقييم',
        'stars': 'نجوم',
        'Verified Purchase': 'شراء موثق',
        'Helpful': 'مفيد',
        'Not Helpful': 'غير مفيد',
        'Report': 'إبلاغ',
        'Share': 'مشاركة',
        'Print': 'طباعة',
        'Email to Friend': 'إرسال بالبريد الإلكتروني لصديق',
        'Wishlist': 'قائمة الرغبات',
        'Compare': 'مقارنة',
        'Quick View': 'عرض سريع',
        'Full Description': 'الوصف الكامل',
        'Technical Data': 'البيانات التقنية',
        'Installation Guide': 'دليل التثبيت',
        'Warranty Information': 'معلومات الضمان',
        'Return Policy': 'سياسة الإرجاع',
        'Shipping Information': 'معلومات الشحن',
        'Payment Options': 'خيارات الدفع',
        'Secure Payment': 'دفع آمن',
        'Free Shipping': 'شحن مجاني',
        'Express Delivery': 'توصيل سريع',
        'Same Day Dispatch': 'إرسال في نفس اليوم',
        'Next Day Delivery': 'توصيل في اليوم التالي',
        'International Shipping': 'شحن دولي',
        'Track Order': 'تتبع الطلب',
        'Order History': 'تاريخ الطلبات',
        'Account': 'الحساب',
        'Login': 'تسجيل الدخول',
        'Register': 'تسجيل',
        'Logout': 'تسجيل الخروج',
        'My Account': 'حسابي',
        'Profile': 'الملف الشخصي',
        'Settings': 'الإعدادات',
        'Password': 'كلمة المرور',
        'Change Password': 'تغيير كلمة المرور',
        'Forgot Password': 'نسيت كلمة المرور',
        'Reset Password': 'إعادة تعيين كلمة المرور',
        'New Password': 'كلمة مرور جديدة',
        'Confirm Password': 'تأكيد كلمة المرور',
        'Current Password': 'كلمة المرور الحالية',
        'Update Profile': 'تحديث الملف الشخصي',
        'Personal Information': 'المعلومات الشخصية',
        'Billing Address': 'عنوان الفواتير',
        'Shipping Address': 'عنوان الشحن',
        'Phone Number': 'رقم الهاتف',
        'Date of Birth': 'تاريخ الميلاد',
        'Gender': 'الجنس',
        'Male': 'ذكر',
        'Female': 'أنثى',
        'Other': 'آخر',
        'Prefer not to say': 'أفضل عدم القول',
        'Newsletter': 'النشرة الإخبارية',
        'Subscribe': 'اشتراك',
        'Unsubscribe': 'إلغاء الاشتراك',
        'Terms & Conditions': 'الشروط والأحكام',
        'Privacy Policy': 'سياسة الخصوصية',
        'Cookie Policy': 'سياسة ملفات تعريف الارتباط',
        'Refund Policy': 'سياسة الاسترداد',
        'Shipping Policy': 'سياسة الشحن',
        'About Us': 'من نحن',
        'Our Story': 'قصتنا',
        'Mission & Vision': 'المهمة والرؤية',
        'Team': 'الفريق',
        'Careers': 'الوظائف',
        'Press': 'الصحافة',
        'Blog': 'المدونة',
        'News': 'الأخبار',
        'Events': 'الأحداث',
        'Support': 'الدعم',
        'Help Center': 'مركز المساعدة',
        'FAQ': 'الأسئلة الشائعة',
        'Contact Support': 'اتصال بالدعم',
        'Live Chat': 'الدردشة المباشرة',
        'Phone Support': 'الدعم الهاتفي',
        'Email Support': 'الدعم عبر البريد الإلكتروني',
        'Ticket System': 'نظام التذاكر',
        'Knowledge Base': 'قاعدة المعرفة',
        'User Manuals': 'الكتيبات الإرشادية',
        'Video Tutorials': 'الدروس المرئية',
        'Troubleshooting': 'استكشاف الأخطاء',
        'Maintenance Guides': 'أدلة الصيانة',
        'Installation Guides': 'أدلة التثبيت',
        'Safety Information': 'معلومات السلامة',
        'Recall Information': 'معلومات الاسترجاع',
        'Product Recalls': 'استرجاع المنتجات',
        'Safety Alerts': 'تنبيهات السلامة',
        'Quality Assurance': 'ضمان الجودة',
        'Quality Control': 'مراقبة الجودة',
        'Testing & Certification': 'الاختبار والاعتماد',
        'ISO Certified': 'معتمد من ISO',
        'CE Marked': 'مُعلَّم بـ CE',
        'FDA Approved': 'معتمد من FDA',
        'UL Listed': 'مدرج في UL',
        'RoHS Compliant': 'متوافق مع RoHS',
        'REACH Compliant': 'متوافق مع REACH',
        'Conflict Minerals Free': 'خالي من المعادن المتنازع عليها',
        'Environmentally Friendly': 'صديق للبيئة',
        'Energy Efficient': 'موفر للطاقة',
        'Recyclable': 'قابل لإعادة التدوير',
        'Biodegradable': 'قابل للتحلل البيولوجي',
        'Sustainable': 'مستدام',
        'Green Technology': 'التكنولوجيا الخضراء',
        'Carbon Neutral': 'محايد للكربون',
        'Zero Waste': 'صفر نفايات',
        'Circular Economy': 'الاقتصاد الدائري',
        'Corporate Social Responsibility': 'المسؤولية الاجتماعية للشركات',
        'Community Outreach': 'التواصل المجتمعي',
        'Charitable Giving': 'العطاء الخيري',
        'Volunteer Programs': 'البرامج التطوعية',
        'Educational Initiatives': 'المبادرات التعليمية',
        'Environmental Protection': 'حماية البيئة',
        'Wildlife Conservation': 'حفظ الحياة البرية',
        'Tree Planting': 'زراعة الأشجار',
        'Clean Energy': 'الطاقة النظيفة',
        'Solar Power': 'الطاقة الشمسية',
        'Wind Power': 'طاقة الرياح',
        'Hydroelectric Power': 'الطاقة الكهرومائية',
        'Geothermal Energy': 'الطاقة الحرارية الأرضية',
        'Biomass Energy': 'طاقة الكتلة الحيوية',
        'Nuclear Energy': 'الطاقة النووية',
        'Fossil Fuels': 'الوقود الأحفوري',
        'Coal': 'الفحم',
        'Oil': 'النفط',
        'Natural Gas': 'الغاز الطبيعي',
        'Petroleum': 'البترول',
        'Diesel': 'الديزل',
        'Gasoline': 'البنزين',
        'LPG': 'الغاز البترولي المسال',
        'CNG': 'الغاز الطبيعي المضغوط',
        'Electric': 'كهربائي',
        'Hybrid': 'هجين',
        'Plug-in Hybrid': 'هجين قابل للشحن',
        'Battery Electric': 'كهربائي بالبطارية',
        'Fuel Cell': 'خلية الوقود',
        'Hydrogen': 'الهيدروجين',
        'Biodiesel': 'الوقود الحيوي',
        'Ethanol': 'الإيثانول',
        'Methanol': 'الميثانول',
        'Propane': 'البروبان',
        'Butane': 'البيوتان',
        'Kerosene': 'الكيروسين',
        'Jet Fuel': 'وقود الطائرات',
        'Marine Fuel': 'وقود البحرية',
        'Heavy Fuel Oil': 'زيت الوقود الثقيل',
        'Light Fuel Oil': 'زيت الوقود الخفيف',
        'Residual Fuel Oil': 'زيت الوقود المتبقي',
        'Distillate Fuel Oil': 'زيت الوقود المقطر',
        'Lubricating Oil': 'زيت التشحيم',
        'Hydraulic Oil': 'الزيت الهيدروليكي',
        'Transmission Oil': 'زيت ناقل الحركة',
        'Engine Oil': 'زيت المحرك',
        'Gear Oil': 'زيت التروس',
        'Brake Fluid': 'سائل الفرامل',
        'Coolant': 'سائل التبريد',
        'Antifreeze': 'مضاد التجمد',
        'Windshield Washer Fluid': 'سائل غسيل الزجاج الأمامي',
        'Power Steering Fluid': 'سائل التوجيه المعزز',
        'Clutch Fluid': 'سائل القابض',
        'Differential Oil': 'زيت التفاضل',
        'Transfer Case Oil': 'زيت صندوق التروس المساعد',
        'Manual Transmission Oil': 'زيت ناقل الحركة اليدوي',
        'Automatic Transmission Fluid': 'سائل ناقل الحركة الأوتوماتيكي',
        'CVT Fluid': 'سائل ناقل الحركة المتغير المستمر',
        'Power Take-off Oil': 'زيت صندوق التروس المساعد',
        'Final Drive Oil': 'زيت القيادة النهائية',
        'Axle Oil': 'زيت المحور',
        'Hub Oil': 'زيت المحور',
        'Wheel Bearing Grease': 'شحم محامل العجلات',
        'Universal Joint Grease': 'شحم المفصل العالمي',
        'Chassis Grease': 'شحم الهيكل',
        'Ball Joint Grease': 'شحم المفصل الكروي',
        'Tie Rod Grease': 'شحم قضيب الربط',
        'Steering Gear Grease': 'شحم ترس التوجيه',
        'Suspension Grease': 'شحم التعليق',
        'Shock Absorber Oil': 'زيت ممتص الصدمات',
        'Air Filter Oil': 'زيت فلتر الهواء',
        'Fuel Filter': 'فلتر الوقود',
        'Oil Filter': 'فلتر الزيت',
        'Air Filter': 'فلتر الهواء',
        'Hydraulic Filter': 'الفلتر الهيدروليكي',
        'Transmission Filter': 'فلتر ناقل الحركة',
        'Cabin Filter': 'فلتر المقصورة',
        'Pollen Filter': 'فلتر حبوب اللقاح',
        'Charcoal Filter': 'الفلتر الفحمي',
        'HEPA Filter': 'فلتر HEPA',
        'Water Separator': 'فاصل الماء',
        'Fuel Water Separator': 'فاصل ماء الوقود',
        'Oil Water Separator': 'فاصل ماء الزيت',
        'Air Water Separator': 'فاصل ماء الهواء',
        'Moisture Separator': 'فاصل الرطوبة',
        'Dust Separator': 'فاصل الغبار',
        'Particle Separator': 'فاصل الجسيمات',
        'Centrifugal Separator': 'الفاصل الطرد المركزي',
        'Magnetic Separator': 'الفاصل المغناطيسي',
        'Gravity Separator': 'الفاصل الجاذبي',
        'Cyclone Separator': 'الفاصل الإعصاري',
        'Bag Filter': 'فلتر الكيس',
        'Cartridge Filter': 'فلتر الخرطوشة',
        'Panel Filter': 'فلتر اللوحة',
        'Pleated Filter': 'الفلتر المطوي',
        'Spun Filter': 'الفلتر المغزول',
        'Wire Mesh Filter': 'فلتر الشبكة السلكية',
        'Sintered Filter': 'الفلتر الملبد',
        'Ceramic Filter': 'الفلتر السيراميكي',
        'Paper Filter': 'فلتر الورق',
        'Felt Filter': 'فلتر اللباد',
        'Foam Filter': 'فلتر الرغوة',
        'Stainless Steel Filter': 'فلتر الفولاذ المقاوم للصدأ',
        'Brass Filter': 'فلتر النحاس الأصفر',
        'Aluminum Filter': 'فلتر الألمنيوم',
        'Plastic Filter': 'الفلتر البلاستيكي',
        'Rubber Filter': 'الفلتر المطاطي',
        'Silicone Filter': 'الفلتر السيليكوني',
        'Teflon Filter': 'فلتر التفلون',
        'Nylon Filter': 'فلتر النايلون',
        'Polyester Filter': 'فلتر البوليستر',
        'Polypropylene Filter': 'فلتر البولي بروبيلين',
        'Polyethylene Filter': 'فلتر البولي إيثيلين',
        'PVC Filter': 'فلتر PVC',
        'ABS Filter': 'فلتر ABS',
        'PC Filter': 'فلتر PC',
        'POM Filter': 'فلتر POM',
        'PBT Filter': 'فلتر PBT',
        'PA Filter': 'فلتر PA',
        'PPS Filter': 'فلتر PPS',
        'PEEK Filter': 'فلتر PEEK',
        'PTFE Filter': 'فلتر PTFE',
        'FEP Filter': 'فلتر FEP',
        'PFA Filter': 'فلتر PFA',
        'ETFE Filter': 'فلتر ETFE',
        'ECTFE Filter': 'فلتر ECTFE',
        'PVDF Filter': 'فلتر PVDF',
        'ECTFE Filter': 'فلتر ECTFE',
        'PCTFE Filter': 'فلتر PCTFE',
        'FEP Filter': 'فلتر FEP',
        'PFA Filter': 'فلتر PFA',
        'ETFE Filter': 'فلتر ETFE',
        'ECTFE Filter': 'فلتر ECTFE',
        'PVDF Filter': 'فلتر PVDF',
        'ECTFE Filter': 'فلتر ECTFE',
        'PCTFE Filter': 'فلتر PCTFE'
    }
    
    # Get all HTML files in pages directory
    html_files = glob.glob('pages/**/*.html', recursive=True)
    html_files.extend(glob.glob('pages/*.html'))
    
    print(f"Found {len(html_files)} HTML files to translate to Arabic")
    
    for file_path in html_files:
        print(f"Translating to Arabic: {file_path}")
        
        # Read the file
        with open(file_path, 'r', encoding='utf-8') as f:
            content = f.read()
        
        # Change language to Arabic and direction to RTL
        content = content.replace('lang="en"', 'lang="ar"')
        content = content.replace('lang="ru"', 'lang="ar"')
        content = content.replace('dir="ltr"', 'dir="rtl"')
        
        # Apply translations
        for english, arabic in common_translations.items():
            content = content.replace(english, arabic)
        
        # Fix CSS and JS paths for subdirectory
        content = content.replace('href="assets/', 'href="../assets/')
        content = content.replace('src="assets/', 'src="../assets/')
        content = content.replace('href="database/', 'href="../database/')
        content = content.replace('src="database/', 'src="../database/')
        
        # Write back to file
        with open(file_path, 'w', encoding='utf-8') as f:
            f.write(content)
    
    print("✅ All sub-pages translated to Arabic!")

if __name__ == "__main__":
    translate_subpages_arabic()






