-- God Mode V2 Database Schema
-- Optimized for High-Scale Industrial Search & Programmatic SEO

-- Enable pgvector for future semantic search features
-- create extension if not exists vector;

-- 1. Brands Table (Normalized for SEO structure)
create table brands (
  id bigint generated by default as identity primary key,
  slug text not null unique, -- e.g. 'volvo', 'caterpillar'
  name text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 2. Categories Table (Hierarchical)
create table categories (
  id bigint generated by default as identity primary key,
  slug text not null, -- e.g. 'hydraulics', 'engine-parts'
  name text not null,
  parent_id bigint references categories(id),
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(slug)
);

-- 3. Products Table (The Core 500k Index)
create table products (
  id bigint generated by default as identity primary key,
  part_number text not null, -- Normalized, stripped of special chars
  brand_id bigint references brands(id) not null,
  name text not null, -- Enriched Name
  sku text unique not null, -- Brand + Part Number e.g. 'volvo-11110534'
  description text,
  
  -- Technical Data
  specs jsonb default '{}'::jsonb, -- Key-value pairs of technical specs
  
  -- SEO & Metadata
  slug text not null unique, -- Final URL slug
  meta_title text,
  meta_description text,
  
  -- Embedding for Semantic Search (1536 dim for OpenAI/Gemini)
  -- embedding vector(1536),

  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Index for fast lookup by part number
create index products_part_number_idx on products (part_number);
-- Index for fast lookup by brand
create index products_brand_id_idx on products (brand_id);
-- Gin index for JSONB specs searching (e.g. searching for weight > 100)
create index products_specs_gin_idx on products using gin (specs);

-- 4. Machines / Fitment Table (The "God Mode" Graph)
create table machines (
  id bigint generated by default as identity primary key,
  model text not null, -- e.g. 'A40d', '320D'
  brand_id bigint references brands(id),
  type text, -- 'Excavator', 'Hauler'
  slug text unique,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 5. Product <-> Machine Compatibility (Many-to-Many)
create table product_machines (
  product_id bigint references products(id) on delete cascade,
  machine_id bigint references machines(id) on delete cascade,
  primary key (product_id, machine_id)
);

-- 6. Leads / Inquiries (The "Anti-Cart")
create table leads (
  id bigint generated by default as identity primary key,
  product_id bigint references products(id),
  email text not null,
  phone text,
  company text,
  message text,
  ip_address text,
  status text default 'new', -- new, contacted, closed
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Row Level Security (RLS) - Basic Setup
alter table products enable row level security;
alter table brands enable row level security;
alter table categories enable row level security;
alter table machines enable row level security;
alter table product_machines enable row level security;
alter table leads enable row level security;

-- Public Read Access
create policy "Public products are viewable by everyone" on products for select using (true);
create policy "Public brands are viewable by everyone" on brands for select using (true);
create policy "Public categories are viewable by everyone" on categories for select using (true);
create policy "Public machines are viewable by everyone" on machines for select using (true);
create policy "Public fitment is viewable by everyone" on product_machines for select using (true);

-- Insert allow for leads
create policy "Anyone can insert leads" on leads for insert with check (true);
